print("Hello You!")
print("What is your name?")
print()
name= input()
print()
print(f"Hi there {name}")
print("How old are you "+name+"?" )
print()
age=input()
print()
print("Why are you "+age+"?")

NotImportant= input()
print("You are strange "+name)
print("What's your stance on Hats?")

Stance_on_hats= input() 
print("I agree")
print("What\'s your name again?")

false_name=input()
print(f"That's not your name. Earlier you said your name was \"{name}\" ")